backintime (1.3.2) unstable; urgency=low
  * Fix bug: Tests no longer work with Python 3.10 (https://github.com/bit-team/backintime/issues/1175)
 -- Germar Reitze <germar.reitze@gmail.com>  Sat, 12 Mar 2022 14:23:43 +0100
